Repository snewcomer/cldr-compact-number, pull requests merged in 2019-11, with the labels that each got.

#12 Allows negatives when using 'significantDigits'
  src/math-utils.ts
Labels: bug

#17 [MINOR]: Include en as default
  README.md
  locales/en.ts
  package.json
  priv/es.js
  priv/zh.js
  src/format-utils.ts
  src/format.ts
  test/format.test.ts
  test/locale-data.ts
Labels: enhancement

#19 Sn/update deps 2
  package-lock.json
  package.json
  rollup.config.ts
  src/format-utils.ts
  src/format.ts
  test/format.test.ts
Labels: dependencies
